#!/usr/bin/sh


if [[ -n "$CONFIG" ]] ; then
	PIA_CONF="$CONFIG"
else
	test "$PIA_CONF" || PIA_CONF='/etc/pia-tools.conf'
fi
[[ -r "$PIA_CONF" ]] && . $PIA_CONF




if [[ -z "$TRANSMISSION_SETTINGS_FILE" ]]; then
    TRANSMISSION_SETTINGS_FILE='/home/dl/.config/transmission-daemon/settings.json'
fi
check_transmission() {
    systemctl is-active transmission > /dev/null 2>&1
}
#echo $config
Base_Config=$(basename "$config")
rm -f "/tmp/$Base_Config"
echo 'VIRT_NET_DEV='$dev >> "/tmp/$Base_Config"
echo 'LOCAL_IP='$ifconfig_local >> "/tmp/$Base_Config"

if [[ -n "$VPN_USER" ]]; then
  ip route add "$trusted_ip"/32 via $route_net_gateway table $VPN_USER
  ip route add 0.0.0.0/1 via $route_vpn_gateway table $VPN_USER
  ip route add 128.0.0.0/1 via $route_vpn_gateway table $VPN_USER
  ip route add "$route_network_1"/32 via $route_vpn_gateway table $VPN_USER
  ip route add $ifconfig_remote dev $dev scope link src $ifconfig_local table $VPN_USER
  if [[ `ip rule list | grep -c 0x3` == 0 ]]; then
    ip rule add from all fwmark 0x3 lookup $VPN_USER
  fi
  ip route append default via 127.0.0.1 dev lo table $VPN_USER
  ip route flush cache
fi

sed -i "s/.*bind-address-ipv4.*/    \"bind-address-ipv4\": \"$ifconfig_local\",/g" $TRANSMISSION_SETTINGS_FILE

    pkill -HUP transmission-da
( /usr/bin/sleep 60 ; pia-tools -r ) &

exit 0
